INSERT INTO my_table (id, name, age, country) VALUES ('1', 'Alice', '30', 'Kenya');
INSERT INTO my_table (id, name, age, country) VALUES ('2', 'Bob', '25', 'Uganda');
INSERT INTO my_table (id, name, age, country) VALUES ('3', 'Carol', '35', 'Kenya');
INSERT INTO my_table (id, name, age, country) VALUES ('4', 'David', '28', 'Nigeria');
INSERT INTO my_table (id, name, age, country) VALUES ('5', 'Eva', '40', 'South Africa');
INSERT INTO my_table (id, name, age, country) VALUES ('6', 'Frank', '33', 'Ethiopia');
INSERT INTO my_table (id, name, age, country) VALUES ('7', 'Grace', '27', 'Tanzania');
INSERT INTO my_table (id, name, age, country) VALUES ('8', 'Henry', '45', 'Kenya');
INSERT INTO my_table (id, name, age, country) VALUES ('9', 'Ivy', '22', 'Uganda');
INSERT INTO my_table (id, name, age, country) VALUES ('10', 'Jack', '38', 'Egypt');
INSERT INTO my_table (id, name, age, country) VALUES ('11', 'Karen', '29', 'Nigeria');
INSERT INTO my_table (id, name, age, country) VALUES ('12', 'Leo', '31', 'South Africa');
INSERT INTO my_table (id, name, age, country) VALUES ('13', 'Mona', '26', 'Kenya');
INSERT INTO my_table (id, name, age, country) VALUES ('14', 'Ned', '36', 'Ghana');
INSERT INTO my_table (id, name, age, country) VALUES ('15', 'Olivia', '24', 'Uganda');
INSERT INTO my_table (id, name, age, country) VALUES ('16', 'Peter', '42', 'Tanzania');
INSERT INTO my_table (id, name, age, country) VALUES ('17', 'Queen', '37', 'Kenya');
INSERT INTO my_table (id, name, age, country) VALUES ('18', 'Raj', '23', 'Egypt');
INSERT INTO my_table (id, name, age, country) VALUES ('19', 'Sam', '34', 'Ghana');
INSERT INTO my_table (id, name, age, country) VALUES ('20', 'Tina', '39', 'South Africa');
INSERT INTO my_table (id, name, age, country) VALUES ('21', 'Umar', '41', 'Nigeria');
INSERT INTO my_table (id, name, age, country) VALUES ('22', 'Victor', '32', 'Ethiopia');
INSERT INTO my_table (id, name, age, country) VALUES ('23', 'Wendy', '28', 'Uganda');
INSERT INTO my_table (id, name, age, country) VALUES ('24', 'Xavier', '30', 'Tanzania');
INSERT INTO my_table (id, name, age, country) VALUES ('25', 'Yara', '21', 'Kenya');
INSERT INTO my_table (id, name, age, country) VALUES ('26', 'Zane', '35', 'Egypt');
INSERT INTO my_table (id, name, age, country) VALUES ('27', 'Amani', '27', 'Kenya');
INSERT INTO my_table (id, name, age, country) VALUES ('28', 'Brenda', '33', 'Uganda');
INSERT INTO my_table (id, name, age, country) VALUES ('29', 'Collins', '29', 'Nigeria');
INSERT INTO my_table (id, name, age, country) VALUES ('30', 'Diana', '40', 'Ghana');
INSERT INTO my_table (id, name, age, country) VALUES ('31', 'Elijah', '31', 'Tanzania');
INSERT INTO my_table (id, name, age, country) VALUES ('32', 'Fatima', '22', 'South Africa');
INSERT INTO my_table (id, name, age, country) VALUES ('33', 'George', '38', 'Ethiopia');
INSERT INTO my_table (id, name, age, country) VALUES ('34', 'Hilda', '24', 'Kenya');
INSERT INTO my_table (id, name, age, country) VALUES ('35', 'Ibrahim', '36', 'Egypt');
INSERT INTO my_table (id, name, age, country) VALUES ('36', 'Jenny', '23', 'Nigeria');
INSERT INTO my_table (id, name, age, country) VALUES ('37', 'Kofi', '39', 'Ghana');
INSERT INTO my_table (id, name, age, country) VALUES ('38', 'Linda', '30', 'Uganda');
INSERT INTO my_table (id, name, age, country) VALUES ('39', 'Mohamed', '28', 'Ethiopia');
INSERT INTO my_table (id, name, age, country) VALUES ('40', 'Nora', '27', 'Kenya');
